export const HomePageTheme = {
  pageBackground: '#f8fafc',
  heroBackground: '#ffffff',
  heroButtonPrimary: '#0ea5e9',
  heroButtonPrimaryHover: '#0284c7',
  heroButtonSecondary: 'transparent',
  heroButtonSecondaryHover: '#f0f9ff',
  heroButtonSecondaryText: '#0ea5e9',
  heroButtonSecondaryBorder: '#0ea5e9',
  sectionBackground: '#f0f9ff',
  showcaseBackground: 'linear-gradient(135deg, #0ea5e9 0%, #2563eb 100%)',
  showcaseBackgroundFallback: '#0ea5e9',
  showcaseTextPrimary: '#ffffff',
  showcaseTextSecondary: '#e0f2fe',
  textPrimary: '#0f172a',
  textSecondary: '#475569',
};
