export const EMAIL_TYPES = {
  VERIFICATION: 'VERIFICATION',
  VERIFICATION_CODE: 'VERIFICATION_CODE',
  PASSWORD_RESET: 'PASSWORD_RESET',
  WELCOME: 'WELCOME',
  PHONE_UPDATE: 'PHONE_UPDATE',
  NOTIFICATION: 'NOTIFICATION',
  OFFER_RECEIVED: 'OFFER_RECEIVED',
  OFFER_COUNTER_RECEIVED: 'OFFER_COUNTER_RECEIVED',
  OFFER_ACCEPTED: 'OFFER_ACCEPTED',
  OFFER_REJECTED: 'OFFER_REJECTED',
  OFFER_EXPIRED: 'OFFER_EXPIRED',
  OFFER_COMPLETED: 'OFFER_COMPLETED',
  PROMOTIONAL: 'PROMOTIONAL',
  PAYMENT_VERIFICATION: 'PAYMENT_VERIFICATION',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_RECEIPT: 'PAYMENT_RECEIPT',
  AGREEMENT_UPDATED: 'AGREEMENT_UPDATED',
  AGREEMENT_UPDATE: 'AGREEMENT_UPDATE',
  SYSTEM: 'SYSTEM',
  ORDER_CONFIRMATION: 'ORDER_CONFIRMATION',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_COMPLETED: 'ORDER_COMPLETED',
  ORDER_REFUNDED: 'ORDER_REFUNDED',
  SALE_NOTIFICATION: 'SALE_NOTIFICATION',
  MEMBERSHIP_ACTIVATED: 'MEMBERSHIP_ACTIVATED',
  MEMBERSHIP_UPGRADE: 'MEMBERSHIP_UPGRADE',
  GREAT_SELLER: 'GREAT_SELLER',
  PRICE_CHANGE: 'PRICE_CHANGE',
  NEW_LISTING: 'NEW_LISTING',
  NEW_LISTING_NOTIFICATION: 'NEW_LISTING_NOTIFICATION',
  AUDIT_ALERT: 'AUDIT_ALERT'
};

export const EmailDto = (data) => ({
  id: data.id || null,
  recipientEmail: data.recipientEmail || '',
  senderEmail: data.senderEmail || '',
  subject: data.subject || '',
  content: data.content || '',
  emailType: data.emailType || EMAIL_TYPES.SYSTEM,
  sentAt: data.sentAt || null,
  createdAt: data.createdAt || null,
  isRead: data.isRead || false
});

export const EMAIL_TYPE_LABELS = {
  [EMAIL_TYPES.VERIFICATION]: 'Doğrulama Kodu',
  [EMAIL_TYPES.VERIFICATION_CODE]: 'Doğrulama Kodu',
  [EMAIL_TYPES.PASSWORD_RESET]: 'Şifre Sıfırlama',
  [EMAIL_TYPES.WELCOME]: 'Hoş Geldiniz',
  [EMAIL_TYPES.PHONE_UPDATE]: 'Telefon Güncelleme',
  [EMAIL_TYPES.NOTIFICATION]: 'Bildirim',
  [EMAIL_TYPES.OFFER_RECEIVED]: 'Yeni Teklif Geldi',
  [EMAIL_TYPES.OFFER_COUNTER_RECEIVED]: 'Karşı Teklif',
  [EMAIL_TYPES.OFFER_ACCEPTED]: 'Teklif Kabul Edildi',
  [EMAIL_TYPES.OFFER_REJECTED]: 'Teklif Reddedildi',
  [EMAIL_TYPES.OFFER_EXPIRED]: 'Teklif Zaman Aşımı',
  [EMAIL_TYPES.OFFER_COMPLETED]: 'Teklif Tamamlandı',
  [EMAIL_TYPES.PROMOTIONAL]: 'Kampanya / Tanıtım',
  [EMAIL_TYPES.PAYMENT_VERIFICATION]: 'Ödeme 2FA Onayı',
  [EMAIL_TYPES.PAYMENT_SUCCESS]: 'Ödeme Alındısı',
  [EMAIL_TYPES.PAYMENT_RECEIPT]: 'Ödeme Makbuzu',
  [EMAIL_TYPES.AGREEMENT_UPDATED]: 'Sözleşme Güncellemesi',
  [EMAIL_TYPES.AGREEMENT_UPDATE]: 'Sözleşme Güncellemesi',
  [EMAIL_TYPES.SYSTEM]: 'Sistem Bildirimi',
  [EMAIL_TYPES.ORDER_CONFIRMATION]: 'Sipariş Onayı',
  [EMAIL_TYPES.ORDER_CANCELLED]: 'Sipariş İptali',
  [EMAIL_TYPES.ORDER_COMPLETED]: 'Sipariş Tamamlandı',
  [EMAIL_TYPES.ORDER_REFUNDED]: 'Sipariş İadesi',
  [EMAIL_TYPES.SALE_NOTIFICATION]: 'Ürün Satıldı (Satıcı)',
  [EMAIL_TYPES.MEMBERSHIP_ACTIVATED]: 'Premium Üyelik',
  [EMAIL_TYPES.MEMBERSHIP_UPGRADE]: 'Premium Üyelik',
  [EMAIL_TYPES.GREAT_SELLER]: 'Great Seller Rozeti',
  [EMAIL_TYPES.PRICE_CHANGE]: 'Fiyat Düşüş Fırsatı',
  [EMAIL_TYPES.NEW_LISTING]: 'Yeni İlan Bildirimi',
  [EMAIL_TYPES.NEW_LISTING_NOTIFICATION]: 'Yeni İlan Bildirimi',
  [EMAIL_TYPES.AUDIT_ALERT]: 'Güvenlik Uyarısı'
};

export const EMAIL_TYPE_BADGE_COLORS = {
  [EMAIL_TYPES.VERIFICATION]: 'bg-amber-50 text-amber-700 border-amber-200',
  [EMAIL_TYPES.VERIFICATION_CODE]: 'bg-amber-50 text-amber-700 border-amber-200',
  [EMAIL_TYPES.PASSWORD_RESET]: 'bg-rose-50 text-rose-700 border-rose-200',
  [EMAIL_TYPES.WELCOME]: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  [EMAIL_TYPES.PHONE_UPDATE]: 'bg-amber-50 text-amber-700 border-amber-200',
  [EMAIL_TYPES.NOTIFICATION]: 'bg-blue-50 text-blue-700 border-blue-200',
  [EMAIL_TYPES.OFFER_RECEIVED]: 'bg-indigo-50 text-indigo-700 border-indigo-200',
  [EMAIL_TYPES.OFFER_COUNTER_RECEIVED]: 'bg-indigo-50 text-indigo-700 border-indigo-200',
  [EMAIL_TYPES.OFFER_ACCEPTED]: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  [EMAIL_TYPES.OFFER_REJECTED]: 'bg-rose-50 text-rose-700 border-rose-200',
  [EMAIL_TYPES.OFFER_EXPIRED]: 'bg-slate-100 text-slate-600 border-slate-200',
  [EMAIL_TYPES.OFFER_COMPLETED]: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  [EMAIL_TYPES.PROMOTIONAL]: 'bg-purple-50 text-purple-700 border-purple-200',
  [EMAIL_TYPES.PAYMENT_VERIFICATION]: 'bg-amber-50 text-amber-700 border-amber-200',
  [EMAIL_TYPES.PAYMENT_SUCCESS]: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  [EMAIL_TYPES.PAYMENT_RECEIPT]: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  [EMAIL_TYPES.AGREEMENT_UPDATED]: 'bg-slate-100 text-slate-700 border-slate-200',
  [EMAIL_TYPES.AGREEMENT_UPDATE]: 'bg-slate-100 text-slate-700 border-slate-200',
  [EMAIL_TYPES.SYSTEM]: 'bg-slate-100 text-slate-700 border-slate-200',
  [EMAIL_TYPES.ORDER_CONFIRMATION]: 'bg-blue-50 text-blue-700 border-blue-200',
  [EMAIL_TYPES.ORDER_CANCELLED]: 'bg-rose-50 text-rose-700 border-rose-200',
  [EMAIL_TYPES.ORDER_COMPLETED]: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  [EMAIL_TYPES.ORDER_REFUNDED]: 'bg-amber-50 text-amber-700 border-amber-200',
  [EMAIL_TYPES.SALE_NOTIFICATION]: 'bg-purple-50 text-purple-700 border-purple-200',
  [EMAIL_TYPES.MEMBERSHIP_ACTIVATED]: 'bg-violet-50 text-violet-700 border-violet-200',
  [EMAIL_TYPES.MEMBERSHIP_UPGRADE]: 'bg-violet-50 text-violet-700 border-violet-200',
  [EMAIL_TYPES.GREAT_SELLER]: 'bg-amber-50 text-amber-700 border-amber-200',
  [EMAIL_TYPES.PRICE_CHANGE]: 'bg-teal-50 text-teal-700 border-teal-200',
  [EMAIL_TYPES.NEW_LISTING]: 'bg-sky-50 text-sky-700 border-sky-200',
  [EMAIL_TYPES.NEW_LISTING_NOTIFICATION]: 'bg-sky-50 text-sky-700 border-sky-200',
  [EMAIL_TYPES.AUDIT_ALERT]: 'bg-rose-50 text-rose-700 border-rose-200'
};
