const PATH_MATCHERS = [
    { test: (p) => /^\/listings\/[^/]+\/edit$/.test(p), page: 'EditListingPage' },
    { test: (p) => p === '/listings/create', page: 'CreateListingPage' },
    { test: (p) => /^\/listings\/[^/]+$/.test(p), page: 'ListingDetailPage' },
    { test: (p) => /^\/lists\/[^/]+$/.test(p), page: 'FavoriteListDetailPage' },
    { test: (p) => /^\/reviews\/received\/[^/]+$/.test(p), page: 'UserReviewsPage' },
    { test: (p) => /^\/reviews\/given\/[^/]+$/.test(p), page: 'UserReviewsPage' },
    { test: (p) => /^\/users\/[^/]+\/reviews$/.test(p), page: 'UserReviewsPage' },
    { test: (p) => /^\/users\/[^/]+$/.test(p), page: 'UserProfilePage' },
    { test: (p) => p === '/login', page: 'LoginPage' },
    { test: (p) => p === '/auth/callback', page: 'OAuthCallbackPage' },
    { test: (p) => p === '/auth/error', page: 'OAuthErrorPage' },
    { test: (p) => p === '/auth/complete', page: 'OAuthCompletePage' },
    { test: (p) => p === '/register', page: 'RegisterPage' },
    { test: (p) => p === '/forgot-password', page: 'ForgotPasswordPage' },
    { test: (p) => p === '/', page: 'HomePage' },
    { test: (p) => p === '/listings', page: 'ListingsPage' },
    { test: (p) => p === '/dashboard', page: 'DashboardPage' },
    { test: (p) => p === '/dashboard/seller', page: 'SellerDashboardPage' },
    { test: (p) => p === '/dashboard/buyer', page: 'BuyerDashboardPage' },
    { test: (p) => p === '/profile', page: 'ProfilePage' },
    { test: (p) => p === '/change-password', page: 'ChangePasswordPage' },
    { test: (p) => p === '/verify-account', page: 'AccountVerificationPage' },
    { test: (p) => p === '/my-listings', page: 'MyListingsPage' },
    { test: (p) => p === '/complaints', page: 'ComplaintsPage' },
    { test: (p) => p === '/favorites', page: 'FavoritesPage' },
    { test: (p) => p === '/payments/listing-fee', page: 'PayListingFeePage' },
    { test: (p) => p === '/payment-methods', page: 'PaymentMethodsPage' },
    { test: (p) => p === '/payments', page: 'PaymentsPage' },
    { test: (p) => p === '/emails', page: 'EmailsPage' },
    { test: (p) => p === '/chat', page: 'ChatPage' },
    { test: (p) => p === '/agreements/all', page: 'AgreementsPage' },
    { test: (p) => p === '/profile/orders', page: 'MyOrdersPage' },
    { test: (p) => p === '/profile/i-sold', page: 'ISoldPage' },
    { test: (p) => p === '/security', page: 'SecurityPage' },
    { test: (p) => p === '/cart', page: 'ShoppingCartPage' },
    { test: (p) => p === '/checkout', page: 'CheckoutPage' },
    { test: (p) => p === '/my-coupons', page: 'MyCouponsPage' },
    { test: (p) => p === '/offers', page: 'OffersPage' },
];

export function getPageName(pathname) {
    const found = PATH_MATCHERS.find((m) => m.test(pathname || ''));
    return found ? found.page : null;
}
