# Üretim: SPRING_PROFILES_ACTIVE=prod
spring:
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.security.oauth2.client: INFO
    org.springframework.security.oauth2.core: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
