
export const AGREEMENT_TYPES = {
  TERMS_OF_SERVICE: 'TERMS_OF_SERVICE',
  PRIVACY_POLICY: 'PRIVACY_POLICY',
  KVKK: 'KVKK',
  DISTANCE_SELLING: 'DISTANCE_SELLING',
  PAYMENT_TERMS: 'PAYMENT_TERMS',
};

export const AGREEMENT_TYPE_LABELS = {
  [AGREEMENT_TYPES.TERMS_OF_SERVICE]: 'Terms Of Service',
  [AGREEMENT_TYPES.PRIVACY_POLICY]: 'Privacy Policy',
  [AGREEMENT_TYPES.KVKK]: 'KVKK',
  [AGREEMENT_TYPES.DISTANCE_SELLING]: 'Distance Selling Agreement',
  [AGREEMENT_TYPES.PAYMENT_TERMS]: 'Payment Terms Agreement',
};

