
export const AGREEMENT_TYPES = {
  TERMS_OF_SERVICE: 'TERMS_OF_SERVICE',
  PRIVACY_POLICY: 'PRIVACY_POLICY',
  KVKK: 'KVKK',
};


export const AGREEMENT_TYPE_LABELS = {
  [AGREEMENT_TYPES.TERMS_OF_SERVICE]: 'Terms Of Service',
  [AGREEMENT_TYPES.PRIVACY_POLICY]: 'Privacy Policy',
  [AGREEMENT_TYPES.KVKK]: 'KVKK',
};

