package com.serhat.secondhand.listing.domain.entity.enums;

public enum Color {
    WHITE,
    BLACK,
    SILVER,
    GRAY,
    NARDO_GRAY,
    GUNMETAL,
    RED,
    ROSSO_CORSA,
    DEEP_BLACK,
    PEARL_WHITE,
    METALLIC_GRAY,
    CANDY_RED,
    FOREST_GREEN,
    SUNSET_ORANGE,
    ROYAL_PURPLE,
    CHAMPAGNE_GOLD,
    BLUE,
    MIDNIGHT_BLUE,
    ATLANTIC_BLUE,
    BRITISH_RACING_GREEN,
    GREEN,
    YELLOW,
    SUNBURST_YELLOW,
    ORANGE,
    LAVA_ORANGE,
    BROWN,
    BEIGE,
    PURPLE_AMETHYST,
    MATTE_BLACK
}
