export const API_BASE_URL = 'http://localhost:8080/api';

export const API_ENDPOINTS = {
    AUTH: {
        LOGIN: '/auth/login',
        REGISTER: '/auth/register',
        LOGOUT: '/auth/logout',
        REFRESH: '/auth/refresh',
        OAUTH_COMPLETE: '/auth/oauth2/complete',
        FORGOT_PASSWORD: '/auth/password/forgot',
        RESET_PASSWORD: '/auth/password/reset',
        CHANGE_PASSWORD: '/auth/password/change',
        REVOKE_ALL_SESSIONS: '/auth/revoke-all-sessions',
    },
    USER: {
        ME: '/v1/users/me',
        UPDATE_EMAIL: '/v1/users/email',
        UPDATE_PHONE: '/v1/users/phone',
        VERIFY: '/v1/users/verification/verify',
        SEND_VERIFICATION: '/v1/users/verification/send',
        BY_ID: (id) => `/v1/users/${id}`,
        SEARCH: '/v1/users/search',
        AUDIT_LOGS: '/v1/users/audit-logs',
    },
    LISTINGS: {
        ALL: '/v1/listings/allListings',
        MY_LISTINGS: '/v1/listings/my-listings',
        BY_ID: (id) => `/v1/listings/${id}`,
        BULK: '/v1/listings/bulk',
        BY_LISTING_NO: (listingNo) => `/v1/listings/search/listing-no/${listingNo}`,
        SEARCH: '/v1/listings/search',
        CREATE: '/v1/listings',
        DELETE: (id) => `/v1/listings/${id}`,
        MARK_SOLD: (id) => `/v1/listings/${id}/mark-sold`,
        ACTIVATE: (id) => `/v1/listings/${id}/reactivate`,
        DEACTIVATE: (id) => `/v1/listings/${id}/deactivate`,
        STATISTICS: '/v1/listings/statistics',
        BY_USER: (userId) => `/v1/users/${userId}/listings`,
        FILTER: '/v1/listings/filter',
        TRACK_VIEW: (id) => `/v1/listings/${id}/view`,
        VIEW_STATS: (id) => `/v1/listings/${id}/view-stats`,
        MY_LISTINGS_VIEW_STATS: '/v1/listings/my-listings/view-stats',
    },
    PAYMENTS: {
        CREATE: '/v1/payments/pay',
        LISTING_FEE_PAYMENT: '/v1/payments/listings/pay-fee',
        MY_PAYMENTS: '/v1/payments/my-payments',
        STATISTICS: '/v1/payments/statistics',
        LISTING_FEE_CONFIG: '/v1/payments/listing-fee-config',
        INITIATE_VERIFICATION: '/v1/payments/initiate-verification',
    },
    ORDERS: {
        CHECKOUT: '/v1/orders/checkout',
        LIST_MY_ORDERS: '/v1/orders',
        LIST_SELLER_ORDERS: '/v1/orders/seller',
        GET_SELLER_ORDER_DETAILS: (id) => `/v1/orders/seller/${id}`,
        GET_PENDING_ESCROW_AMOUNT: '/v1/orders/seller/pending-escrow-amount',
        PENDING_COMPLETION: '/v1/orders/pending-completion',
        GET_BY_ORDER_NUMBER: (orderNumber) => `/v1/orders?orderNumber=${encodeURIComponent(orderNumber)}`,
        GET_ORDER_DETAILS: (id) => `/v1/orders/${id}`,
        CANCEL_ORDER: (id) => `/v1/orders/${id}/cancel`,
        REFUND_ORDER: (id) => `/v1/orders/${id}/refund`,
        COMPLETE_ORDER: (id) => `/v1/orders/${id}/complete`,
        UPDATE_ORDER_NAME: (id) => `/v1/orders/${id}/name`,
    },
    DASHBOARD: {
        SELLER: '/v1/dashboard/seller',                                                  // GET - Seller dashboard
        BUYER: '/v1/dashboard/buyer',                                                    // GET - Buyer dashboard
    },
    CREDIT_CARDS: {
        GET_ALL: '/v1/credit-card',
        CREATE: '/v1/credit-card',
        DELETE: '/v1/credit-card',
        EXISTS: '/v1/credit-card/exists',
        AVAILABLE_CREDIT: '/v1/credit-card/available-credit',
    },
    COMPLAINTS: {
        CREATE: '/v1/complaints',
        MY_COMPLAINTS: '/v1/users/me/complaints',
        ABOUT_ME: '/v1/users/me/complaints/received',
    },
    BANK_ACCOUNTS: {
        GET_ALL: '/v1/bank',
        CREATE: '/v1/bank',
        DELETE: '/v1/bank',
        EXISTS: '/v1/bank/exists',
        BALANCE: '/v1/bank/balance',
    },
    EMAILS: {
        MY_EMAILS: '/v1/emails/my-emails',
        UNREAD_COUNT: '/v1/emails/unread-count',
        DELETE: (emailId) => `/v1/emails/${emailId}`,
        DELETE_ALL: '/v1/emails',
    },
    ENUMS: {
        LISTING_TYPES: '/v1/enums/listing-types',
        LISTING_STATUSES: '/v1/enums/listing-statuses',
        CAR_BRANDS: '/v1/enums/car-brands',
        FUEL_TYPES: '/v1/enums/fuel-types',
        COLORS: '/v1/enums/colors',
        DOORS: '/v1/enums/doors',
        CURRENCIES: '/v1/enums/currencies',
        GEAR_TYPES: '/v1/enums/gear-types',
        SEAT_COUNTS: '/v1/enums/seat-counts',
        ELECTRONIC_TYPES: '/v1/enums/electronic-types',
        ELECTRONIC_BRANDS: '/v1/enums/electronic-brands',
        PROCESSORS: '/v1/enums/processors',
        DRIVETRAINS: '/v1/enums/drivetrains',
        BODY_TYPES: '/v1/enums/body-types',
        REAL_ESTATE_TYPES: '/v1/enums/real-estate-types',
        REAL_ESTATE_AD_TYPES: '/v1/enums/real-estate-ad-types',
        HEATING_TYPES: '/v1/enums/heating-types',
        OWNER_TYPES: '/v1/enums/owner-types',
        CLOTHING_BRANDS: '/v1/enums/clothing-brands',
        CLOTHING_TYPES: '/v1/enums/clothing-types',
        CLOTHING_CONDITIONS: '/v1/enums/clothing-conditions',
        CLOTHING_GENDERS: '/v1/enums/clothing-genders',
        CLOTHING_CATEGORIES: '/v1/enums/clothing-categories',
        BOOK_GENRES: '/v1/enums/book-genres',
        BOOK_LANGUAGES: '/v1/enums/book-languages',
        BOOK_FORMATS: '/v1/enums/book-formats',
        BOOK_CONDITIONS: '/v1/enums/book-conditions',
        GENDERS: '/v1/enums/genders',
        SPORT_DISCIPLINES: '/v1/enums/sport-disciplines',
        SPORT_EQUIPMENT_TYPES: '/v1/enums/sport-equipment-types',
        SPORT_CONDITIONS: '/v1/enums/sport-conditions',
        PAYMENT_TYPES: '/v1/enums/payment-types',
        SHIPPING_STATUSES: '/v1/enums/shipping-statuses',
        ORDER_STATUSES: '/v1/enums/order-statuses',
        EMAIL_TYPES: '/v1/enums/email-types',
        AUDIT_EVENT_TYPES: '/v1/enums/audit-event-types',
        AUDIT_EVENT_STATUSES: '/v1/enums/audit-event-statuses',
        LISTING_FEE_CONFIG: '/v1/enums/listing-fee-config',
        SHOWCASE_PRICING_CONFIG: '/v1/enums/showcase-pricing-config',
        AGREEMENT_GROUPS: '/v1/enums/agreement-groups',
        AGREEMENT_TYPES: '/v1/enums/agreement-types',
        ALL: '/v1/enums/all',
    },
    VEHICLES: {
        CREATE: '/v1/vehicles/create-listing',
        BY_ID: (id) => `/v1/vehicles/${id}`,
        UPDATE: (id) => `/v1/vehicles/${id}`,
        BY_BRAND_MODEL: (brandId, modelId) => `/v1/vehicles/brand/${brandId}/model/${modelId}`,
        BRANDS: '/v1/vehicles/brands',
        FILTER: '/v1/vehicles/filter',
    },
    ELECTRONICS: {
        CREATE: '/v1/electronics/create-listing',
        BY_ID: (id) => `/v1/electronics/${id}`,
        UPDATE: (id) => `/v1/electronics/${id}`,
        BY_TYPE: (electronicType) => `/v1/electronics/electronicType/${electronicType}`,
        FILTER: '/v1/electronics/filter',
    },
    REAL_ESTATES: {
        CREATE: '/v1/realEstates/create-listing',
        BY_ID: (id) => `/v1/realEstates/${id}`,
        UPDATE: (id) => `/v1/realEstates/${id}`,
        FILTER: '/v1/realEstates/filter',
    },
    CLOTHING: {
        CREATE: '/v1/clothing/create-listing',
        BY_ID: (id) => `/v1/clothing/${id}`,
        UPDATE: (id) => `/v1/clothing/${id}`,
        BY_BRAND_TYPE: (brand, clothingType) => `/v1/clothing/brand/${brand}/type/${clothingType}`,
        FILTER: '/v1/clothing/filter',
    },
    BOOKS: {
        CREATE: '/v1/books/create-listing',
        BY_ID: (id) => `/v1/books/${id}`,
        UPDATE: (id) => `/v1/books/${id}`,
        FILTER: '/v1/books/filter',
    },
    SPORTS: {
        CREATE: '/v1/sports/create-listing',
        BY_ID: (id) => `/v1/sports/${id}`,
        UPDATE: (id) => `/v1/sports/${id}`,
        FILTER: '/v1/sports/filter',
    },
    FAVORITES: {
        ADD: '/favorites',
        TOGGLE: '/favorites/toggle',
        MY_FAVORITES: '/favorites',
        CHECK: (listingId) => `/favorites/check/${listingId}`,
        TOP: '/favorites/top',
        TOP_LISTINGS: '/favorites/top-listings',
    },
    AGREEMENTS: {
        INITIALIZE: '/agreements/initialize',
        ALL: '/agreements',
        REQUIRED: '/agreements/required',
        BY_TYPE: (agreementType) => `/agreements/${agreementType}`,
        CREATE: '/agreements',
        UPDATE_BY_ID: (agreementId) => `/agreements/${agreementId}`,
        UPDATE_BY_TYPE: (agreementType) => `/agreements/type/${agreementType}`,
        ACCEPT: '/agreements/accept',
        USER_AGREEMENTS: '/agreements/user/agreements',
        USER_STATUS_ALL: '/agreements/user/status',
        USER_STATUS_BY_TYPE: (agreementType) => `/agreements/user/status/${agreementType}`,
        USER_ACCEPTANCE_HISTORY: (agreementId) => `/agreements/user/acceptance-history/${agreementId}`,
        ADMIN_ACCEPT_ALL: '/agreements/admin/accept-all-users',
    },
    CHAT: {
        CREATE_ROOM: '/chat/rooms',
        USER_ROOMS: '/chat/rooms/user',
        DIRECT_ROOM: '/chat/rooms/direct',
        CREATE_LISTING_ROOM: (listingId) => `/chat/rooms/listing/${listingId}`,
        
        SEND_MESSAGE: '/chat/messages',
        ROOM_MESSAGES: (chatRoomId) => `/chat/rooms/${chatRoomId}/messages`,
        MARK_READ: (chatRoomId) => `/chat/rooms/${chatRoomId}/messages/read`,
        
        ALL_USER_MESSAGES: '/chat/messages/user',
        TOTAL_UNREAD_COUNT: `/chat/messages/unread-count`,
        
        DELETE_CONVERSATION: (chatRoomId) => `/chat/rooms/${chatRoomId}`,
        DELETE_MESSAGE: (messageId) => `/chat/messages/${messageId}`,
    },
    ADDRESS: {
        ALL: '/addresses',
        CREATE: '/addresses',
        UPDATE: (id) => `/addresses/${id}`,
        DELETE: (id) => `/addresses/${id}`,
        SELECT_MAIN: (id) => `/addresses/${id}/main`,
    },
    PRICE_HISTORY: {
        BY_LISTING: (listingId) => `/v1/price-history/listing/${listingId}`,
        LATEST: (listingId) => `/v1/price-history/listing/${listingId}/latest`,
        EXISTS: (listingId) => `/v1/price-history/listing/${listingId}/exists`,
    },
    AUDIT_LOGS: {
        USER_BY_EMAIL: (userEmail) => `/admin/audit-logs/user/${userEmail}`,
        USER_BY_ID: (userId) => `/admin/audit-logs/user/id/${userId}`,
        BY_EVENT_TYPE: (eventType) => `/admin/audit-logs/event-type/${eventType}`,
        BY_DATE_RANGE: '/admin/audit-logs/date-range',
        FAILED_ATTEMPTS_BY_USER: (userEmail) => `/admin/audit-logs/failed-attempts/user/${userEmail}`,
        FAILED_ATTEMPTS_BY_IP: (ipAddress) => `/admin/audit-logs/failed-attempts/ip/${ipAddress}`,
    },
    AUDIT_ENUMS: {
        EVENT_TYPES: '/audit/enums/event-types',
        EVENT_STATUSES: '/audit/enums/event-statuses',
        ALL: '/audit/enums/all',
    },
    CART: {
        GET_ITEMS: '/v1/cart',
        ADD_ITEM: '/v1/cart/items',
        UPDATE_ITEM: (listingId) => `/v1/cart/items/${listingId}`,
        REMOVE_ITEM: (listingId) => `/v1/cart/items/${listingId}`,
        CLEAR_CART: '/v1/cart/items',
        GET_COUNT: '/v1/cart/count',
        CHECK_ITEM: (listingId) => `/v1/cart/check/${listingId}`,
    },
    COUPONS: {
        PREVIEW: '/v1/coupons/preview',
        ACTIVE: '/v1/coupons/active',
    },
    CAMPAIGNS: {
        SELLER: '/v1/seller/campaigns',
        BY_ID: (id) => `/v1/seller/campaigns/${id}`,
    },
    OFFERS: {
        CREATE: '/v1/offers',
        MADE: '/v1/users/me/offers/made',
        RECEIVED: '/v1/users/me/offers/received',
        BY_ID: (id) => `/v1/offers/${id}`,
        ACCEPT: (id) => `/v1/offers/${id}/accept`,
        REJECT: (id) => `/v1/offers/${id}/reject`,
        COUNTER: (id) => `/v1/offers/${id}/counter`,
    },
    REVIEWS: {
        CREATE_REVIEW: '/v1/reviews',
        GET_REVIEWS_RECEIVED: '/v1/users/me/reviews/received',
        GET_REVIEWS_RECEIVED_BY: (userId) => `/v1/users/${userId}/reviews/received`,
        GET_REVIEWS_WRITTEN_BY: (userId) => `/v1/users/${userId}/reviews/written`,
        GET_USER_REVIEW_STATS: (userId) => `/v1/users/${userId}/review-stats`,
        GET_REVIEWS_BY_ORDER_ITEMS: '/v1/reviews',
        GET_REVIEW_BY_ORDER_ITEM: (orderItemId) => `/v1/orders/items/${orderItemId}/review`,
        GET_REVIEWS_FOR_LISTING: (listingId) => `/v1/listings/${listingId}/reviews`,
        GET_LISTING_REVIEW_STATS: (listingId) => `/v1/listings/${listingId}/review-stats`,
    },
    EWALLET: {
        CREATE: '/ewallet',
        GET: '/ewallet',
        UPDATE_LIMITS: '/ewallet/limits',
        UPDATE_SPENDING_WARNING: '/ewallet/update/spendingWarning',
        REMOVE_SPENDING_WARNING: '/ewallet/update/spendingWarning',
        DEPOSIT: '/ewallet/deposit',
        WITHDRAW: '/ewallet/withdraw',
        TRANSACTIONS: '/ewallet/transactions',
        CHECK_BALANCE: '/ewallet/balance/check',
    },
    SHOWCASES: {
        CREATE: '/showcases',
        ACTIVE: '/showcases/active',
        MY_SHOWCASES: '/showcases/my',
        EXTEND: (id) => `/showcases/${id}/extend`,
        CANCEL: (id) => `/showcases/${id}/cancel`,
        PRICING_CONFIG: '/showcases/pricing-config',
    },
    EXCHANGE: {
        RATE: (from, to) => `/v1/exchange/${from}/${to}`,
    },
    IMAGES: {
        UPLOAD: '/images/upload',
        DELETE: '/images/delete',
    },
    FOLLOW: {
        FOLLOW: (userId) => `/follow/${userId}`,
        UNFOLLOW: (userId) => `/follow/${userId}`,
        TOGGLE_NOTIFICATIONS: (userId) => `/follow/${userId}/notifications`,
        FOLLOWING: '/follow/following',
        FOLLOWERS: '/follow/followers',
        STATS: (userId) => `/follow/stats/${userId}`,
        CHECK: (userId) => `/follow/check/${userId}`,
        USER_FOLLOWERS: (userId) => `/follow/user/${userId}/followers`,
        USER_FOLLOWING: (userId) => `/follow/user/${userId}/following`,
    },
    FAVORITE_LISTS: {
        CREATE: '/favorite-lists',
        MY_LISTS: '/favorite-lists/my',
        USER_LISTS: (userId) => `/favorite-lists/user/${userId}`,
        POPULAR: '/favorite-lists/popular',
        BY_ID: (listId) => `/favorite-lists/${listId}`,
        UPDATE: (listId) => `/favorite-lists/${listId}`,
        DELETE: (listId) => `/favorite-lists/${listId}`,
        ADD_ITEM: (listId) => `/favorite-lists/${listId}/items`,
        REMOVE_ITEM: (listId, listingId) => `/favorite-lists/${listId}/items/${listingId}`,
        LIKE: (listId) => `/favorite-lists/${listId}/like`,
        UNLIKE: (listId) => `/favorite-lists/${listId}/like`,
        LISTING_LISTS: (listingId) => `/favorite-lists/listing/${listingId}/lists`,
    },
    NOTIFICATIONS: {
        ALL: '/v1/notifications',
        UNREAD_COUNT: '/v1/notifications/unread-count',
        MARK_AS_READ: (id) => `/v1/notifications/${id}/read`,
        MARK_ALL_AS_READ: '/v1/notifications/read-all',
    },
};