export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    AUTH_CALLBACK: '/auth/callback',
    AUTH_ERROR: '/auth/error',
    AUTH_COMPLETE: '/auth/complete',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    CHANGE_PASSWORD: '/change-password',
    VERIFY_ACCOUNT: '/verify-account',
    DASHBOARD: '/dashboard',
    PROFILE: '/profile',
    LISTINGS: '/listings',
    MY_LISTINGS: '/my-listings',
    COMPLAINTS: '/complaints',
    USER_PROFILE: (userId) => `/users/${userId}`,
    FAVORITES: '/favorites',
    LISTING_DETAIL: (id) => `/listings/${id}`,
    EDIT_LISTING: (id) => `/listings/${id}/edit`,
    VEHICLE_DETAIL: '/vehicles/:id',
    CREATE_LISTING: '/listings/create',
    CREATE_REAL_ESTATE: '/real-estates/create',
    CREATE_CLOTHING: '/clothing/create',
    CLOTHING_DETAIL: '/clothing/:id',
    PAYMENTS: '/payments',
    PAY_LISTING_FEE: '/payments/listing-fee',
    PAYMENT_METHODS: '/payment-methods',
    EMAILS: '/emails',
    CHAT: '/chat',
    AGREEMENTS: '/agreements',
    AGREEMENTS_ALL: '/agreements/all',
    SECURITY: '/security',
    SHOPPING_CART: '/cart',
    MY_ORDERS: '/profile/orders',
    USER_REVIEWS: (userId) => `/users/${userId}/reviews`,
};