export const CANCEL_REFUND_REASONS = {
  DEFECTIVE_PRODUCT: 'DEFECTIVE_PRODUCT',
  WRONG_ITEM: 'WRONG_ITEM',
  NOT_AS_DESCRIBED: 'NOT_AS_DESCRIBED',
  CHANGED_MIND: 'CHANGED_MIND',
  DELAYED_DELIVERY: 'DELAYED_DELIVERY',
  OTHER: 'OTHER',
};

export const CANCEL_REFUND_REASON_LABELS = {
  [CANCEL_REFUND_REASONS.DEFECTIVE_PRODUCT]: 'Defective Product',
  [CANCEL_REFUND_REASONS.WRONG_ITEM]: 'Wrong Item',
  [CANCEL_REFUND_REASONS.NOT_AS_DESCRIBED]: 'Not as Described',
  [CANCEL_REFUND_REASONS.CHANGED_MIND]: 'Changed Mind',
  [CANCEL_REFUND_REASONS.DELAYED_DELIVERY]: 'Delayed Delivery',
  [CANCEL_REFUND_REASONS.OTHER]: 'Other',
};

export const getCancelRefundReasonLabel = (reason) => {
  return CANCEL_REFUND_REASON_LABELS[reason] || reason;
};



