import { get, post, del } from '../../../services/api/request';
import { API_ENDPOINTS } from '../../../constants/apiEndpoints';

export const bankService = {
  // Get all bank accounts
  getAllBankAccounts: async () => get(API_ENDPOINTS.BANK_ACCOUNTS.GET_ALL),

  // Create new bank account (no data needed, all generated by backend)
  createBankAccount: async () => post(API_ENDPOINTS.BANK_ACCOUNTS.CREATE),

  // Get user's bank account
  getBankAccount: async () => get(API_ENDPOINTS.BANK_ACCOUNTS.GET_ALL),

  // Delete bank account
  deleteBankAccount: async () => del(API_ENDPOINTS.BANK_ACCOUNTS.DELETE),

  // Check if bank account exists
  checkBankAccountExists: async () => get(API_ENDPOINTS.BANK_ACCOUNTS.EXISTS),

  // Get bank balance
  getBankBalance: async () => get(API_ENDPOINTS.BANK_ACCOUNTS.BALANCE),
};