import apiClient from '../../../services/api/config';
import { API_ENDPOINTS } from '../../../constants/apiEndpoints';

export const bankService = {
  // Get all bank accounts
  getAllBankAccounts: async () => {
    const response = await apiClient.get(API_ENDPOINTS.BANK_ACCOUNTS.GET_ALL);
    return response.data;
  },

  // Create new bank account (no data needed, all generated by backend)
  createBankAccount: async () => {
    const response = await apiClient.post(API_ENDPOINTS.BANK_ACCOUNTS.CREATE);
    return response.data;
  },

  // Get user's bank account
  getBankAccount: async () => {
    const response = await apiClient.get(API_ENDPOINTS.BANK_ACCOUNTS.GET_ALL);
    return response.data;
  },

  // Delete bank account
  deleteBankAccount: async () => {
    const response = await apiClient.delete(API_ENDPOINTS.BANK_ACCOUNTS.DELETE);
    return response.data;
  },

  // Check if bank account exists
  checkBankAccountExists: async () => {
    const response = await apiClient.get(API_ENDPOINTS.BANK_ACCOUNTS.EXISTS);
    return response.data;
  },

  // Get bank balance
  getBankBalance: async () => {
    const response = await apiClient.get(API_ENDPOINTS.BANK_ACCOUNTS.BALANCE);
    return response.data;
  },
};