package com.serhat.secondhand.notification.entity.enums;

public enum NotificationType {
    OFFER_RECEIVED,
    OFFER_ACCEPTED,
    OFFER_REJECTED,
    OFFER_COUNTERED,
    OFFER_EXPIRED,
    ORDER_CREATED,
    ORDER_STATUS_CHANGED,
    ORDER_CANCELLED,
    ORDER_RECEIVED,
    CHAT_MESSAGE_RECEIVED,
    LISTING_PRICE_DROPPED,
    LISTING_NEW_FROM_FOLLOWED,
    LISTING_SOLD,
    REVIEW_RECEIVED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    AGREEMENT_UPDATED
}

