export const BooksListingDTO = {
    id: '',
    listingNo: '',
    title: '',
    description: '',
    price: 0,
    currency: '',
    status: '',
    city: '',
    district: '',
    createdAt: '',
    updatedAt: '',
    sellerName: '',
    sellerSurname: '',
    sellerId: 0,
    type: '',
    author: '',
    genre: '',
    publicationYear: '',
    pageCount: 0,
    language: '',
    format: '',
    condition: ''
};

export const createBooksCreateRequest = (data) => ({
  title: data.title,
  description: data.description,
  price: data.price,
  currency: data.currency || 'TRY',
  city: data.city,
  district: data.district,
  author: data.author,
  genre: data.genre,
  language: data.language,
  publicationYear: data.publicationYear,
  pageCount: data.pageCount,
  format: data.format,
  condition: data.condition,
  isbn: data.isbn || undefined,
  imageUrl: data.imageUrl || undefined,
});

export const createBooksUpdateRequest = (data) => ({
  title: data.title ?? undefined,
  description: data.description ?? undefined,
  price: data.price ?? undefined,
  currency: data.currency ?? undefined,
  city: data.city ?? undefined,
  district: data.district ?? undefined,
  author: data.author ?? undefined,
  genre: data.genre ?? undefined,
  language: data.language ?? undefined,
  publicationYear: data.publicationYear ?? undefined,
  pageCount: data.pageCount ?? undefined,
  format: data.format ?? undefined,
  condition: data.condition ?? undefined,
  isbn: data.isbn ?? undefined,
  imageUrl: data.imageUrl ?? undefined,
});

export const createBooksListingDto = (data) => ({
  id: data.id,
  listingNo: data.listingNo,
  title: data.title,
  description: data.description,
  price: data.price,
  currency: data.currency,
  status: data.status,
  listingFeePaid: data.listingFeePaid,
  city: data.city,
  district: data.district,
  createdAt: data.createdAt,
  updatedAt: data.updatedAt,
  sellerName: data.sellerName,
  sellerSurname: data.sellerSurname,
  sellerId: data.sellerId,
  type: data.type,
  author: data.author,
  genre: data.genre,
  language: data.language,
  publicationYear: data.publicationYear,
  pageCount: data.pageCount,
  format: data.format,
  condition: data.condition,
  isbn: data.isbn,
  imageUrl: data.imageUrl,
});


export const createBooksFilterRequest = (data) => ({
  type: 'BOOKS',
  listingType: 'BOOKS',
  status: data.status || 'ACTIVE',
  city: data.city?.trim() || '',
  district: data.district?.trim() || '',
  minPrice: parseFloat(data.minPrice) || null,
  maxPrice: parseFloat(data.maxPrice) || null,
  currency: data.currency || 'TRY',
  genres: Array.isArray(data.genres) ? data.genres : [],
  languages: Array.isArray(data.languages) ? data.languages : [],
  formats: Array.isArray(data.formats) ? data.formats : [],
  conditions: Array.isArray(data.conditions) ? data.conditions : [],
  minYear: parseInt(data.minYear) || null,
  maxYear: parseInt(data.maxYear) || null,
  minPageCount: parseInt(data.minPageCount) || null,
  maxPageCount: parseInt(data.maxPageCount) || null,
  sortBy: data.sortBy || 'createdAt',
  sortDirection: data.sortDirection || 'DESC',
  page: parseInt(data.page) || 0,
  size: parseInt(data.size) || 20,
});


