-- V13: Add premium fields to real_estate_listings table

ALTER TABLE real_estate_listings ADD COLUMN gross_area_m2 INT;
ALTER TABLE real_estate_listings ADD COLUMN net_area_m2 INT;
ALTER TABLE real_estate_listings ADD COLUMN usage_status VARCHAR(60);
ALTER TABLE real_estate_listings ADD COLUMN deed_status VARCHAR(60);
ALTER TABLE real_estate_listings ADD COLUMN room_config_key VARCHAR(60);
ALTER TABLE real_estate_listings ADD COLUMN heating_type_key VARCHAR(60);
ALTER TABLE real_estate_listings ADD COLUMN floor_number INT;
ALTER TABLE real_estate_listings ADD COLUMN total_floors INT;
ALTER TABLE real_estate_listings ADD COLUMN has_balcony BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE real_estate_listings ADD COLUMN has_elevator BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE real_estate_listings ADD COLUMN has_parking BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE real_estate_listings ADD COLUMN monthly_fee DECIMAL(19, 2);
ALTER TABLE real_estate_listings ADD COLUMN is_in_site BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE real_estate_listings ADD COLUMN site_name VARCHAR(120);
ALTER TABLE real_estate_listings ADD COLUMN garden_area_m2 INT;
ALTER TABLE real_estate_listings ADD COLUMN land_share_m2 INT;
ALTER TABLE real_estate_listings ADD COLUMN has_pool BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE real_estate_listings ADD COLUMN zoning_status_key VARCHAR(60);
ALTER TABLE real_estate_listings ADD COLUMN parcel_no VARCHAR(30);
ALTER TABLE real_estate_listings ADD COLUMN block_no VARCHAR(30);
ALTER TABLE real_estate_listings ADD COLUMN sheet_no VARCHAR(30);
ALTER TABLE real_estate_listings ADD COLUMN floor_area_ratio DECIMAL(19, 2);
ALTER TABLE real_estate_listings ADD COLUMN height_limit DECIMAL(19, 2);
ALTER TABLE real_estate_listings ADD COLUMN road_frontage DECIMAL(19, 2);
ALTER TABLE real_estate_listings ADD COLUMN infrastructure_status_key VARCHAR(60);
ALTER TABLE real_estate_listings ADD COLUMN water_source VARCHAR(60);
ALTER TABLE real_estate_listings ADD COLUMN electricity_available BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE real_estate_listings ADD COLUMN road_access BOOLEAN DEFAULT FALSE NOT NULL;
