ALTER TABLE users ADD COLUMN IF NOT EXISTS plan VARCHAR(20) NOT NULL DEFAULT 'FREE';
ALTER TABLE users ADD COLUMN IF NOT EXISTS plan_expiry TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS ai_listing_quota INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_aura_usage INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_aura_reset_date DATE;

UPDATE users SET plan = 'FREE', ai_listing_quota = 1, daily_aura_usage = 0;
