export const API_BASE_URL = 'http://localhost:8080/api';

export const API_ENDPOINTS = {
    AUTH: {
        LOGIN: '/auth/login',
        REGISTER: '/auth/register',
        LOGOUT: '/auth/logout',
        REFRESH: '/auth/refresh',
        FORGOT_PASSWORD: '/auth/password/forgot',
        RESET_PASSWORD: '/auth/password/reset',
        CHANGE_PASSWORD: '/auth/password/change',
        VALIDATE: '/auth/validate',
    },
    USER: {
        ME: '/v1/users/me',
        UPDATE_EMAIL: '/v1/users/email',
        UPDATE_PHONE: '/v1/users/phone',
        VERIFY: '/v1/users/verification/verify',
        SEND_VERIFICATION: '/v1/users/verification/send',
    },
    LISTINGS: {
        ALL: '/v1/listings/allListings',
        MY_LISTINGS: '/v1/listings/my-listings',
        BY_STATUS: (status) => `/v1/listings/my-listings/status/${status}`,
        BY_ID: (id) => `/v1/listings/${id}`,
        BY_LISTING_NO: (listingNo) => `/v1/listings/search/listing-no/${listingNo}`,
        CREATE: '/v1/listings',
        DELETE: (id) => `/v1/listings/${id}`,
        MARK_SOLD: (id) => `/v1/listings/${id}/mark-sold`,
        ACTIVATE: (id) => `/v1/listings/${id}/reactivate`,
        DEACTIVATE: (id) => `/v1/listings/${id}/deactivate`,
        STATISTICS: '/v1/listings/statistics',
        BY_TYPE_ACTIVE: (listingType) => `/v1/listings/type/${listingType}/active`,
        BY_TYPE_ORDERED: (listingType) => `/v1/listings/type/${listingType}/ordered`,
        FILTER: '/v1/listings/filter',
    },
    PAYMENTS: {
        CREATE: '/v1/payments/pay',
        LISTING_FEE_PAYMENT: '/v1/payments/listings/pay-fee',
        MY_PAYMENTS: '/v1/payments/my-payments',
        STATISTICS: '/v1/payments/statistics',
        LISTING_FEE_CONFIG: '/v1/payments/listing-fee-config',
    },
    CREDIT_CARDS: {
        GET_ALL: '/v1/credit-card',
        CREATE: '/v1/credit-card',
        DELETE: '/v1/credit-card',
        EXISTS: '/v1/credit-card/exists',
        AVAILABLE_CREDIT: '/v1/credit-card/available-credit',
    },
    BANK_ACCOUNTS: {
        GET_ALL: '/v1/bank',
        CREATE: '/v1/bank',
        DELETE: '/v1/bank',
        EXISTS: '/v1/bank/exists',
        BALANCE: '/v1/bank/balance',
    },
    EMAILS: {
        MY_EMAILS: '/v1/emails/my-emails',
        DELETE: (emailId) => `/v1/emails/delete/${emailId}`,
        DELETE_ALL:  `/v1/emails/deleteAll`,
    },
    ENUMS: {
        LISTING_TYPES: '/v1/enums/listing-types',
        LISTING_STATUSES: '/v1/enums/listing-statuses',
        CAR_BRANDS: '/v1/enums/car-brands',
        FUEL_TYPES: '/v1/enums/fuel-types',
        COLORS: '/v1/enums/colors',
        DOORS: '/v1/enums/doors',
        CURRENCIES: '/v1/enums/currencies',
        GEAR_TYPES: '/v1/enums/gear-types',
        SEAT_COUNTS: '/v1/enums/seat-counts',
        ELECTRONIC_TYPES: '/v1/enums/electronic-types',
        ELECTRONIC_BRANDS: '/v1/enums/electronic-brands'},
    VEHICLES: {
        CREATE: '/v1/vehicles/create-listing',
        BY_ID: (id) => `/v1/vehicles/${id}`,
        UPDATE: (id) => `/v1/vehicles/${id}`,
        BY_BRAND_MODEL: (brand, model) => `/v1/vehicles/brand/${brand}/model/${model}`,
        BRANDS: '/v1/vehicles/brands',
    },
    ELECTRONICS: {
        CREATE: '/v1/electronics/create-listing',
        BY_ID: (id) => `/v1/electronics/${id}`,
        UPDATE: (id) => `/v1/electronics/${id}`,
        BY_TYPE: (electronicType) => `/v1/electronics/electronicType/${electronicType}`,
    },
    FAVORITES: {
        ADD: '/favorites',
        REMOVE: (listingId) => `/favorites/${listingId}`,
        TOGGLE: '/favorites/toggle',
        MY_FAVORITES: '/favorites',
        STATS: (listingId) => `/favorites/stats/${listingId}`,
        BULK_STATS: '/favorites/stats',
        CHECK: (listingId) => `/favorites/check/${listingId}`,
        COUNT: (listingId) => `/favorites/count/${listingId}`,
        IDS: '/favorites/ids',
        TOP: '/favorites/top',
    },
};