export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    DASHBOARD: '/dashboard',
    PROFILE: '/profile',
    LISTINGS: '/listings',
    MY_LISTINGS: '/my-listings',
    LISTING_DETAIL: '/listings/:id',
    CREATE_LISTING: '/listings/create',
    PAYMENTS: '/payments',
    PAY_LISTING_FEE: '/payments/listing-fee',
    CREDIT_CARDS: '/payments/credit-cards',
    BANK_ACCOUNTS: '/payments/bank-accounts',
};