export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    CHANGE_PASSWORD: '/change-password',
    VERIFY_ACCOUNT: '/verify-account',
    DASHBOARD: '/dashboard',
    PROFILE: '/profile',
    LISTINGS: '/listings',
    MY_LISTINGS: '/my-listings',
    MY_LISTINGS_INACTIVE: '/my-listings/inactive',
    FAVORITES: '/favorites',
    LISTING_DETAIL: '/listings/:id',
    VEHICLE_DETAIL: '/vehicles/:id',
    VEHICLE_EDIT: '/vehicles/:id/edit',
    CREATE_LISTING: '/listings/create',
    PAYMENTS: '/payments',
    PAY_LISTING_FEE: '/payments/listing-fee',
    CREDIT_CARDS: '/credit-card',
    BANK_ACCOUNTS: '/bank',
    EMAILS: '/emails',
};